# This file contains values from Cookiecutter

default_context:
  project_name: "k2"
  project_description: "k2"
  organization: "kaldi"
  license: "MIT"
  version: "0.1.0"
  github_name: "songmeixu"
  email: "songmeixu@outlook.com"
